### ISSUE TITLE
Typo in base code in Find Sequence

### ISSUE THREAD

**Issue by GusHebblewhite** [CheckiO-Missions/checkio-task-find-sequence#6]
From  https://js.checkio.org/en/mission/find-sequence/

The base code has an uneven number of square brackets in the input type. This leads to some confusing errors that might throw of a noobie (like me!).
```
function findSequence(values: number[][]]): boolean {
    // your code here
    return false;
}
```

Solution:
Delete the final `]` in `number[][]]`

**Comment by oduvan** [comment]
Thank you
